
public enum PIPE {

	STRAIGHTPIPE(0), BENTPIPE(1), TPIPE(2), CROSSPIPE(3), UPINWATERSTORE(4), RIGHTINWATERSTORE(5), DOWNINWATERSTORE(6),
	LEFTINWATERSTORE(7), STRAIGHTPIPEWITHWATER(8), BENTPIPEWITHWATER(9), TPIPEWITHWATER(10), CROSSPIPEWITHONEWATER(11),
	CROSSPIPEWITHTWOWATER(12), UPINWATERSTOREWITHWATER(13), RIGHTINWATERSTOREWITHWATER(14),
	DOWNINWATERSTOREWITHWATER(15), LEFTINWATERSTOREWITHWATER(16);

	private int index;

	PIPE(int index) {
		this.index = index;
	}

	public int getIndex() {
		return index;
	}

}
